PoC: revamp environment
contember/admin pull request #321
Opened 2022-05-13 14:38 UTC by matej21

2022-05-13 15:09 UTC, VojtaStanek commented
fixes #303

2022-05-16 12:33 UTC, JanTvrdik requested changes
> Reviewed 20 of 32 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/321)* status: 20 of 32 files reviewed, 9 unresolved discussions (waiting on @JanTvrdik and @matej21)

___
*[`packages/binding/src/coreComponents/EntityListSubTree.tsx` line 73 at r1](https://reviewable.io/reviews/contember/admin/321#-N2B722qByYeVLLWuHBD:-N2B722qByYeVLLWuHBE:undefined) ([raw file](https://github.com/contember/admin/blob/4d7b416a1810db72a3f7dc1645e09125598d3e98/packages/binding/src/coreComponents/EntityListSubTree.tsx#L73)):*
> ```XML
> 
> 			const rootWhere = { id: NIL_UUID } as const
> 			return oldEnvironment.withVariables(props.variables)
> ```





_Suggestion:_
```XML
			return oldEnvironment
				.withVariables(props.variables)
				.withSubtree({
```
___
*[`packages/binding/src/dao/Environment.ts` line 65 at r1](https://reviewable.io/reviews/contember/admin/321#-N2BCUTD9Emo5LEybAz_:-N2BCUTD9Emo5LEybAza:bjutalw) ([raw file](https://github.com/contember/admin/blob/4d7b416a1810db72a3f7dc1645e09125598d3e98/packages/binding/src/dao/Environment.ts#L65)):*
> ```XML
> 			([name, value]) => {
> 				if (name === 'labelMiddleware') {
> 					throw new BindingError('You cannot pass labelMiddleware to withVariables method. Use withLabelMiddleware instead.')
> ```

Maybe console.warning instead to reduce BC break?
___
*[`packages/binding/src/dao/Environment.ts` line 74 at r1](https://reviewable.io/reviews/contember/admin/321#-N2BB3As63hcLf0BMxGP:-N2BB3As63hcLf0BMxGQ:b-g79mk9) ([raw file](https://github.com/contember/admin/blob/4d7b416a1810db72a3f7dc1645e09125598d3e98/packages/binding/src/dao/Environment.ts#L74)):*
> ```XML
> 		)
> 		const newVariables = { ...this.options.variables }
> 		for (const [newName, newValue] of resolvedVariablesEntries) {
> ```

inline variable resolving



_Suggestion:_
```XML
		const newVariables = { ...this.options.variables }
		for (const [newName, newValue] of variables) {
			if (newName === 'labelMiddleware') {
				throw new BindingError('You cannot pass labelMiddleware to withVariables method. Use withLabelMiddleware instead.')
			} else if (newValue === undefined) {
				delete newVariables[newName]
			} else if (typeof newValue === 'function') {
				newVariables[newName] = newValue(this)
			} else {
				newVariables[newName] = newValue
			}
		}
```
___
*[`packages/binding/src/dao/Environment.ts` line 97 at r1](https://reviewable.io/reviews/contember/admin/321#-N2Bm64F8HSIciuht3Ts:-N2Bm64F8HSIciuht3Tt:bb2y8ry) ([raw file](https://github.com/contember/admin/blob/4d7b416a1810db72a3f7dc1645e09125598d3e98/packages/binding/src/dao/Environment.ts#L97)):*
> ```XML
> 			...dimensions,
> 		}
> 		if (JSON.stringify(newDimensions) === JSON.stringify(this.options.dimensions)) {
> ```

use fast equal
___
*[`packages/binding/src/dao/Environment.ts` line 127 at r1](https://reviewable.io/reviews/contember/admin/321#-N2BmSqU0Mz6vKu_6Iu5:-N2BmSqU0Mz6vKu_6Iu6:b-4gtqvl) ([raw file](https://github.com/contember/admin/blob/4d7b416a1810db72a3f7dc1645e09125598d3e98/packages/binding/src/dao/Environment.ts#L127)):*
> ```XML
> 			throw new BindingError(`Cannot merge two environments with different tree position.`)
> 		}
> 		if (!equal(this.options.parameters, other.options.parameters)) {
> ```

should be possible to compare with `===`
___
*[`packages/binding/src/dao/Environment.ts` line 130 at r1](https://reviewable.io/reviews/contember/admin/321#-N2BmW0AAFgfu2Ptu44b:-N2BmW0AAFgfu2Ptu44c:b-4gtqvl) ([raw file](https://github.com/contember/admin/blob/4d7b416a1810db72a3f7dc1645e09125598d3e98/packages/binding/src/dao/Environment.ts#L130)):*
> ```XML
> 			throw new BindingError(`Cannot merge two environments with different parameters.`)
> 		}
> 		if (!equal(this.options.dimensions, other.options.dimensions)) {
> ```

should be possible to compare with `===`
___
*[`packages/binding/src/dao/Environment.ts` line 138 at r1](https://reviewable.io/reviews/contember/admin/321#-N2Bmkvx-vqP4m5g7yFx:-N2Bmkvx-vqP4m5g7yFy:b-pyabou) ([raw file](https://github.com/contember/admin/blob/4d7b416a1810db72a3f7dc1645e09125598d3e98/packages/binding/src/dao/Environment.ts#L138)):*
> ```XML
> 		for (const key in other.options.variables) {
> 			if (key in this.options.variables && !equal(this.options.variables[key], other.options.variables[key])) {
> 				throw new BindingError(`Cannot merge two environments with different value of variable ${key}.`)
> ```

include the two values in error message
___
*[`packages/binding/src/dao/Environment.ts` line 153 at r1](https://reviewable.io/reviews/contember/admin/321#-N2BouUY4feJN8VduInv:-N2BouUY4feJN8VduInw:b-zeizfc) ([raw file](https://github.com/contember/admin/blob/4d7b416a1810db72a3f7dc1645e09125598d3e98/packages/binding/src/dao/Environment.ts#L153)):*
> ```XML
> 			case 'rootFilter':
> 			case 'rootWhereAsFilter':
> 				return this.options.treePosition?.rootFilter
> ```

emit deprecated warning?
___
*[`packages/binding/src/dao/Environment.ts` line 164 at r1](https://reviewable.io/reviews/contember/admin/321#-N2BpySL4olp4th2nM1M:-N2BpySL4olp4th2nM1N:bvtf427) ([raw file](https://github.com/contember/admin/blob/4d7b416a1810db72a3f7dc1645e09125598d3e98/packages/binding/src/dao/Environment.ts#L164)):*
> ```XML
> 		if (key in this.options.dimensions) {
> 			const dimensionValue = this.options.dimensions[key]
> 			if (dimensionValue.length > 1) {
> ```

why limit dimensions and not variables and parameters;
maybe add new method `resolveScalarValue` which would limit all of them?


<!-- Sent from Reviewable.io -->

2022-05-16 12:33 UTC, JanTvrdik requested changes
> *[Reviewable](https://reviewable.io/reviews/contember/admin/321)* status: 20 of 32 files reviewed, 10 unresolved discussions (waiting on @JanTvrdik and @matej21)

___
*[`packages/binding/src/dao/Environment.ts` line 7 at r1](https://reviewable.io/reviews/contember/admin/321#-N2BquDBDHL50MrlsxHA:-N2BquDBDHL50MrlsxHB:bh4k7f5) ([raw file](https://github.com/contember/admin/blob/4d7b416a1810db72a3f7dc1645e09125598d3e98/packages/binding/src/dao/Environment.ts#L7)):*
> ```XML
> import { Schema } from "../core/schema";
> 
> class Environment {
> ```

less bc breaks


<!-- Sent from Reviewable.io -->

2022-05-17 15:18 UTC, matej21 reviewed
> *[Reviewable](https://reviewable.io/reviews/contember/admin/321)* status: 8 of 48 files reviewed, 10 unresolved discussions (waiting on @JanTvrdik)

___
*[`packages/binding/src/coreComponents/EntityListSubTree.tsx` line 73 at r1](https://reviewable.io/reviews/contember/admin/321#-N2B722qByYeVLLWuHBD:-N2HZILVDe2f5YgBeVo5:b-896fix) ([raw file](https://github.com/contember/admin/blob/4d7b416a1810db72a3f7dc1645e09125598d3e98/packages/binding/src/coreComponents/EntityListSubTree.tsx#L73)):*
> ```XML
> 
> 			const rootWhere = { id: NIL_UUID } as const
> 			return oldEnvironment.withVariables(props.variables)
> ```

Done.
___
*[`packages/binding/src/dao/Environment.ts` line 7 at r1](https://reviewable.io/reviews/contember/admin/321#-N2BquDBDHL50MrlsxHA:-N2H_uq49HTWrC3liAUu:b-896fix) ([raw file](https://github.com/contember/admin/blob/4d7b416a1810db72a3f7dc1645e09125598d3e98/packages/binding/src/dao/Environment.ts#L7)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

less bc breaks
</blockquote></details>

Done.
___
*[`packages/binding/src/dao/Environment.ts` line 65 at r1](https://reviewable.io/reviews/contember/admin/321#-N2BCUTD9Emo5LEybAz_:-N2HZPqe8tEkO9rFsVfc:bgatdt7) ([raw file](https://github.com/contember/admin/blob/4d7b416a1810db72a3f7dc1645e09125598d3e98/packages/binding/src/dao/Environment.ts#L65)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

Maybe console.warning instead to reduce BC break?
</blockquote></details>

I think, it was used only inside SideDimensions, which is back compatible.
___
*[`packages/binding/src/dao/Environment.ts` line 74 at r1](https://reviewable.io/reviews/contember/admin/321#-N2BB3As63hcLf0BMxGP:-N2HZxH07_MFb0JYZHn5:b-896fix) ([raw file](https://github.com/contember/admin/blob/4d7b416a1810db72a3f7dc1645e09125598d3e98/packages/binding/src/dao/Environment.ts#L74)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

inline variable resolving
</blockquote></details>

Done.
___
*[`packages/binding/src/dao/Environment.ts` line 97 at r1](https://reviewable.io/reviews/contember/admin/321#-N2Bm64F8HSIciuht3Ts:-N2H_2sF6lzXDKSqxzIj:b-896fix) ([raw file](https://github.com/contember/admin/blob/4d7b416a1810db72a3f7dc1645e09125598d3e98/packages/binding/src/dao/Environment.ts#L97)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

use fast equal
</blockquote></details>

Done.
___
*[`packages/binding/src/dao/Environment.ts` line 127 at r1](https://reviewable.io/reviews/contember/admin/321#-N2BmSqU0Mz6vKu_6Iu5:-N2H_3ze3kTcEa0yukD9:b-896fix) ([raw file](https://github.com/contember/admin/blob/4d7b416a1810db72a3f7dc1645e09125598d3e98/packages/binding/src/dao/Environment.ts#L127)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

should be possible to compare with `===`
</blockquote></details>

Done.
___
*[`packages/binding/src/dao/Environment.ts` line 130 at r1](https://reviewable.io/reviews/contember/admin/321#-N2BmW0AAFgfu2Ptu44b:-N2H_5AG0AcSgfkeFM8r:b-896fix) ([raw file](https://github.com/contember/admin/blob/4d7b416a1810db72a3f7dc1645e09125598d3e98/packages/binding/src/dao/Environment.ts#L130)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

should be possible to compare with `===`
</blockquote></details>

Done.
___
*[`packages/binding/src/dao/Environment.ts` line 138 at r1](https://reviewable.io/reviews/contember/admin/321#-N2Bmkvx-vqP4m5g7yFx:-N2H_5wP4LR5nLPeoRsv:b-896fix) ([raw file](https://github.com/contember/admin/blob/4d7b416a1810db72a3f7dc1645e09125598d3e98/packages/binding/src/dao/Environment.ts#L138)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

include the two values in error message
</blockquote></details>

Done.
___
*[`packages/binding/src/dao/Environment.ts` line 153 at r1](https://reviewable.io/reviews/contember/admin/321#-N2BouUY4feJN8VduInv:-N2H_vpE4cXrk_0p7xS2:b-896fix) ([raw file](https://github.com/contember/admin/blob/4d7b416a1810db72a3f7dc1645e09125598d3e98/packages/binding/src/dao/Environment.ts#L153)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

emit deprecated warning?
</blockquote></details>

Done.
___
*[`packages/binding/src/dao/Environment.ts` line 164 at r1](https://reviewable.io/reviews/contember/admin/321#-N2BpySL4olp4th2nM1M:-N2H_Ssw3pRiF3pfcPkE:boft63h) ([raw file](https://github.com/contember/admin/blob/4d7b416a1810db72a3f7dc1645e09125598d3e98/packages/binding/src/dao/Environment.ts#L164)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

why limit dimensions and not variables and parameters;
maybe add new method `resolveScalarValue` which would limit all of them?
</blockquote></details>

moved back to Parser


<!-- Sent from Reviewable.io -->

2022-05-25 08:19 UTC, matej21 reviewed
> *[Reviewable](https://reviewable.io/reviews/contember/admin/321)* status: 40 of 49 files reviewed, 13 unresolved discussions (waiting on @JanTvrdik)

___
*[`packages/binding/src/dao/Environment.ts` line 48 at r3](https://reviewable.io/reviews/contember/admin/321#-N2qEFAq92xwZuO9hjoW:-N2uC7uk507KLWAWZrbJ:b-896fix) ([raw file](https://github.com/contember/admin/blob/695f424b409c584cc4d5adba186cf555dd67561f/packages/binding/src/dao/Environment.ts#L48)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

why accept object? 
</blockquote></details>

Done.
___
*[`packages/binding/src/dao/Environment.ts` line 55 at r3](https://reviewable.io/reviews/contember/admin/321#-N2qE9389SENH8HdKR86:-N2uC89pDb5bPO2oODJa:b-896fix) ([raw file](https://github.com/contember/admin/blob/695f424b409c584cc4d5adba186cf555dd67561f/packages/binding/src/dao/Environment.ts#L55)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

better error message?
</blockquote></details>

Done.
___
*[`packages/binding/src/dao/Environment.ts` line 181 at r3](https://reviewable.io/reviews/contember/admin/321#-N2qAHP-0gr4WofBJ_Qs:-N2uCIvjDzlf9H_zHbgc:b-896fix) ([raw file](https://github.com/contember/admin/blob/695f424b409c584cc4d5adba186cf555dd67561f/packages/binding/src/dao/Environment.ts#L181)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

why is this getter instead of normal method? (i.e. how is parent different from schema)?
</blockquote></details>

Done.
___
*[`packages/binding/src/dao/TreeNodeEnvironmentHelper.ts` line 19 at r3](https://reviewable.io/reviews/contember/admin/321#-N2qU22y-HPw2IabfvLf:-N2uCVkl3ChRJHnKLjFb:b-896fix) ([raw file](https://github.com/contember/admin/blob/695f424b409c584cc4d5adba186cf555dd67561f/packages/binding/src/dao/TreeNodeEnvironmentHelper.ts#L19)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

Helper is imho bad class name suffix given what this class does
</blockquote></details>

Done.
___
*[`packages/binding/src/dao/TreeNodeEnvironmentHelper.ts` line 20 at r3](https://reviewable.io/reviews/contember/admin/321#-N2qP1bfEoDce4iF2hCH:-N2uCqkKBU4lqpbZXTaC:b-896fix) ([raw file](https://github.com/contember/admin/blob/695f424b409c584cc4d5adba186cf555dd67561f/packages/binding/src/dao/TreeNodeEnvironmentHelper.ts#L20)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

i would swap argument order in all createEnvironment methods
</blockquote></details>

Done.
___
*[`packages/binding/src/dao/TreeNodeEnvironmentHelper.ts` line 27 at r3](https://reviewable.io/reviews/contember/admin/321#-N2qLWAXBXirSR35eMaO:-N2uCvbC52unlY3KIkku:b-896fix) ([raw file](https://github.com/contember/admin/blob/695f424b409c584cc4d5adba186cf555dd67561f/packages/binding/src/dao/TreeNodeEnvironmentHelper.ts#L27)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

inconsistent line order
</blockquote></details>

Done.
___
*[`packages/binding/src/dao/TreeNodeEnvironmentHelper.ts` line 33 at r3](https://reviewable.io/reviews/contember/admin/321#-N2qPPjEBfUdnE9enHLI:-N2uCwXUBGn08viOyJ_6:b-b6nhnw) ([raw file](https://github.com/contember/admin/blob/695f424b409c584cc4d5adba186cf555dd67561f/packages/binding/src/dao/TreeNodeEnvironmentHelper.ts#L33)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

missing assert that filter is valid? or out-of-scope?
</blockquote></details>

yes, it is out of scope
___
*[`packages/binding/src/dao/TreeNodeEnvironmentHelper.ts` line 35 at r3](https://reviewable.io/reviews/contember/admin/321#-N2qNYnf17FGVUAdw5jI:-N2uI5xu7CkARFcECC5F:b-896fix) ([raw file](https://github.com/contember/admin/blob/695f424b409c584cc4d5adba186cf555dd67561f/packages/binding/src/dao/TreeNodeEnvironmentHelper.ts#L35)):*
> ```XML
> 		this.assertEntityExists(environment.getSchema(), entityList.entityName, 'entity list')
> 
> 		return environment
> ```

Done.
___
*[`packages/binding/src/dao/TreeNodeEnvironmentHelper.ts` line 38 at r3](https://reviewable.io/reviews/contember/admin/321#-N2qMdkYEowCp2jZ40Fg:-N2uDLvM0EpviKCydU3s:b149ujk) ([raw file](https://github.com/contember/admin/blob/695f424b409c584cc4d5adba186cf555dd67561f/packages/binding/src/dao/TreeNodeEnvironmentHelper.ts#L38)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

zero when isCreating is true?
</blockquote></details>

changed to `zero-to-many` - that is even more describing for `not isCreating`, because that may be empty as well
___
*[`packages/binding/src/dao/TreeNodeEnvironmentHelper.ts` line 44 at r3](https://reviewable.io/reviews/contember/admin/321#-N2qOetB0Cxo8zUyATC-:-N2uEBnm9-m8BbVCzd0Z:b-896fix) ([raw file](https://github.com/contember/admin/blob/695f424b409c584cc4d5adba186cf555dd67561f/packages/binding/src/dao/TreeNodeEnvironmentHelper.ts#L44)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

inconsistent flow with createEnvironmentForEntityListSubtree
</blockquote></details>

Done.
___
*[`packages/binding/src/dao/TreeNodeEnvironmentHelper.ts` line 60 at r3](https://reviewable.io/reviews/contember/admin/321#-N2qPIwO3_YpDeQmxdWK:-N2uECJ88cxEvfmRXSHp:bqmig9u) ([raw file](https://github.com/contember/admin/blob/695f424b409c584cc4d5adba186cf555dd67561f/packages/binding/src/dao/TreeNodeEnvironmentHelper.ts#L60)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

missing assert that filter is valid? or out-of-scope?
</blockquote></details>

out of scope
___
*[`packages/binding/src/dao/TreeNodeEnvironmentHelper.ts` line 74 at r3](https://reviewable.io/reviews/contember/admin/321#-N2qWKfv-PMgNlKVUW92:-N2uEZPCE4XoLpNX75kA:b-896fix) ([raw file](https://github.com/contember/admin/blob/695f424b409c584cc4d5adba186cf555dd67561f/packages/binding/src/dao/TreeNodeEnvironmentHelper.ts#L74)):*
> ```XML
> 	): Environment {
> 		const relativeEntityList = QueryLanguage.desugarRelativeEntityList(sugaredRelativeEntityList, environment)
> 		const hasOneEnvironment = TreeNodeEnvironmentHelper.traverseHasOnePath(
> ```

Done.
___
*[`packages/binding/src/dao/TreeNodeEnvironmentHelper.ts` line 120 at r3](https://reviewable.io/reviews/contember/admin/321#-N2qXZf8AcG9nHagYoPO:-N2uGfTW4GmBWFct7i07:b-896fix) ([raw file](https://github.com/contember/admin/blob/695f424b409c584cc4d5adba186cf555dd67561f/packages/binding/src/dao/TreeNodeEnvironmentHelper.ts#L120)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

maybe split to two methods for `many` and `one` case?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-25 10:20 UTC, JanTvrdik requested changes
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/321)* status: all files reviewed, 14 unresolved discussions (waiting on @matej21)

___
*[`packages/binding/src/dao/Environment.ts` line 48 at r4](https://reviewable.io/reviews/contember/admin/321#-N2u_Nfd-QnkHWZa--bL:-N2u_Nfd-QnkHWZa--bM:bl6j6rz) ([raw file](https://github.com/contember/admin/blob/c46033bd1163b7e1ceffc196e6778181efd2c286/packages/binding/src/dao/Environment.ts#L48)):*
> ```XML
> 	}
> 
> 	public withTreeChild(field: string) {
> ```

why not withSubtreeChild? 
___
*[`packages/binding/src/dao/Environment.ts` line 65 at r4](https://reviewable.io/reviews/contember/admin/321#-N2uaIOO7pfHBACJvIjj:-N2uaIOO7pfHBACJvIjk:b3jeh4a) ([raw file](https://github.com/contember/admin/blob/c46033bd1163b7e1ceffc196e6778181efd2c286/packages/binding/src/dao/Environment.ts#L65)):*
> ```XML
> 			subtreeLocation: {
> 				entity: targetEntity,
> 				path: [...this.options.subtreeLocation.path, field],
> ```

given that we store reference to parent environment, why do we need to store the entire path?
___
*[`packages/binding/src/dao/Environment.ts` line 232 at r4](https://reviewable.io/reviews/contember/admin/321#-N2uiQgDAr84Le39LYvP:-N2uiQgDAr84Le39LYvQ:bg37cvc) ([raw file](https://github.com/contember/admin/blob/c46033bd1163b7e1ceffc196e6778181efd2c286/packages/binding/src/dao/Environment.ts#L232)):*
> ```XML
> 	export interface Options {
> 		subtree?: Subtree
> 		subtreeLocation?: SubtreeLocation
> ```

would it be possible to get actually more of a tree like structure? i.e sth like

~~~
RootEntity{List?}Node(entitySchema, filter, cardinality)
  ColumnNode(parent, fieldSchema)
  InnerEntityNode(parent, fieldSchema, entitySchema, filter, cardinality)
  InnerEntityListNode(parent, fieldSchema, entitySchema, filter, cardinality)
~~~
___
*[`packages/binding/src/dao/Environment.ts` line 238 at r4](https://reviewable.io/reviews/contember/admin/321#-N2uhflU49qdy0Kvq7OD:-N2uhflU49qdy0Kvq7OE:brrbev) ([raw file](https://github.com/contember/admin/blob/c46033bd1163b7e1ceffc196e6778181efd2c286/packages/binding/src/dao/Environment.ts#L238)):*
> ```XML
> 		variables: CustomVariables
> 		labelMiddleware: LabelMiddleware
> 		parent?: Environment
> ```

do we need reference to parent environment, or would reference to parent "tree node" be enough?
___
*[`packages/binding/src/dao/Environment.ts` line 242 at r4](https://reviewable.io/reviews/contember/admin/321#-N2udzXb-vtQohUCOIkR:-N2udzXb-vtQohUCOIkS:b-9qtt2) ([raw file](https://github.com/contember/admin/blob/c46033bd1163b7e1ceffc196e6778181efd2c286/packages/binding/src/dao/Environment.ts#L242)):*
> ```XML
> 
> 	export interface Subtree {
> 		entity: string
> ```

is there a reason why do we store entity name instead of reference entity schema object?
___
*[`packages/binding/src/dao/Environment.ts` line 243 at r4](https://reviewable.io/reviews/contember/admin/321#-N2uXe0kE2gIQpGCnbxx:-N2uXe0kE2gIQpGCnbxy:b-5ajr2h) ([raw file](https://github.com/contember/admin/blob/c46033bd1163b7e1ceffc196e6778181efd2c286/packages/binding/src/dao/Environment.ts#L243)):*
> ```XML
> 	export interface Subtree {
> 		entity: string
> 		type: 'list' | 'entity'
> ```

type should be imho be first



_Suggestion:_
```XML
		type: 'list' | 'entity'
		entity: string
```
___
*[`packages/binding/src/dao/Environment.ts` line 249 at r4](https://reviewable.io/reviews/contember/admin/321#-N2ueNLL0lnUMk2huiJz:-N2ueNLL0lnUMk2huiK-:b-htqj7r) ([raw file](https://github.com/contember/admin/blob/c46033bd1163b7e1ceffc196e6778181efd2c286/packages/binding/src/dao/Environment.ts#L249)):*
> ```XML
> 
> 	export interface SubtreeLocation {
> 		path: string[]
> ```

is there a reason why do we store path as string instead of references to field schema object(s)?
___
*[`packages/binding/src/dao/TreeNodeEnvironmentFactory.ts` line 53 at r4](https://reviewable.io/reviews/contember/admin/321#-N2uRy2W92UhStbBrKdL:-N2uRy2W92UhStbBrKdM:buplpo9) ([raw file](https://github.com/contember/admin/blob/c46033bd1163b7e1ceffc196e6778181efd2c286/packages/binding/src/dao/TreeNodeEnvironmentFactory.ts#L53)):*
> ```XML
> 		let rootWhere
> 		let expectedCardinality: Environment.Subtree['expectedCardinality']
> 		let qualifiedSingleEntity
> ```

* incosistent naming with `createEnvironmentForEntityListSubtree` (should be just `entity` or `singleEntity`)
* inconsistent line order of declaration & assignments
___
*[`packages/binding/src/dao/TreeNodeEnvironmentFactory.ts` line 96 at r4](https://reviewable.io/reviews/contember/admin/321#-N2uTAqK2g7qGPTY5x7H:-N2uTAqK2g7qGPTY5x7I:undefined) ([raw file](https://github.com/contember/admin/blob/c46033bd1163b7e1ceffc196e6778181efd2c286/packages/binding/src/dao/TreeNodeEnvironmentFactory.ts#L96)):*
> ```XML
> 
> 		return this.traverseHasOnePath(
> 			environment,
> ```





_Suggestion:_
```XML
		return this.traverseHasOnePath(environment, relativeSingleEntity.hasOneRelationPath)
```
___
*[`packages/binding/src/dao/TreeNodeEnvironmentFactory.ts` line 139 at r4](https://reviewable.io/reviews/contember/admin/321#-N2uQ1Rd7IpGMuvs51Tr:-N2uQ1Rd7IpGMuvs51Ts:undefined) ([raw file](https://github.com/contember/admin/blob/c46033bd1163b7e1ceffc196e6778181efd2c286/packages/binding/src/dao/TreeNodeEnvironmentFactory.ts#L139)):*
> ```XML
> 		const treeLocation = environment.getSubtreeLocation()
> 		const relation = this.getField(environment, field, field => {
> 			if (field.__typename !== '_Relation') {
> ```





_Suggestion:_
```XML
			return field.__typename === '_Relation' && expectedRelationType.includes(field.type)
```
___
*[`packages/binding/src/dao/TreeNodeEnvironmentFactory.ts` line 147 at r4](https://reviewable.io/reviews/contember/admin/321#-N2uVJXZ1W-sqK5ZycId:-N2uVJXZ1W-sqK5ZycIe:b2gj5mj) ([raw file](https://github.com/contember/admin/blob/c46033bd1163b7e1ceffc196e6778181efd2c286/packages/binding/src/dao/TreeNodeEnvironmentFactory.ts#L147)):*
> ```XML
> 			throw new BindingError(
> 				`Invalid field: the name '${field}' on ${this.describeLocation(treeLocation)} ` +
> 				`refers to an ordinary scalar field but is being used as a ${relationDescription} relation.`,
> ```

column may not by scalar in the future; maybe extract "describeField"?
___
*[`packages/binding/src/dao/TreeNodeEnvironmentFactory.ts` line 152 at r4](https://reviewable.io/reviews/contember/admin/321#-N2uTN1k2YnMF3pevywF:-N2uTN1k2YnMF3pevywG:bsq3v1i) ([raw file](https://github.com/contember/admin/blob/c46033bd1163b7e1ceffc196e6778181efd2c286/packages/binding/src/dao/TreeNodeEnvironmentFactory.ts#L152)):*
> ```XML
> 		if (!expectedRelationType.includes(relation.type)) {
> 			throw new BindingError(`Invalid relation: the name '${field}' on ${this.describeLocation(treeLocation)} ` +
> 				`refers to a ${relation.type} relation but is being used as a ${relationDescription}.`)
> ```

maybe extract "describeField"?



_Suggestion:_
```XML
			throw new BindingError(
				`Invalid field: the name '${field}' on ${this.describeLocation(treeLocation)} ` +
				`refers to a ${relation.type} relation but is being used as a ${relationDescription}.`
			)
```
___
*[`packages/binding/src/dao/TreeNodeEnvironmentFactory.ts` line 169 at r4](https://reviewable.io/reviews/contember/admin/321#-N2uTakX9vHEfeDVPHX6:-N2uTakX9vHEfeDVPHX7:bsq3v1i) ([raw file](https://github.com/contember/admin/blob/c46033bd1163b7e1ceffc196e6778181efd2c286/packages/binding/src/dao/TreeNodeEnvironmentFactory.ts#L169)):*
> ```XML
> 		if (field.__typename === '_Relation') {
> 			const treeLocation = environment.getSubtreeLocation()
> 			throw new BindingError(
> ```

maybe extract "describeField"?



_Suggestion:_
```XML
			const treeLocation = environment.getSubtreeLocation()
			throw new BindingError(
				`Invalid field: the name '${fieldName}' on ${this.describeLocation(treeLocation)}` +
				`refers to a ${field.type} relation but is being used as a field.`,
			)
```
___
*[`packages/binding/src/dao/TreeNodeEnvironmentHe [...]

2022-05-25 11:27 UTC, matej21 reviewed
> *[Reviewable](https://reviewable.io/reviews/contember/admin/321)* status: 46 of 49 files reviewed, 14 unresolved discussions (waiting on @JanTvrdik and @matej21)

___
*[`packages/binding/src/dao/Environment.ts` line 48 at r4](https://reviewable.io/reviews/contember/admin/321#-N2u_Nfd-QnkHWZa--bL:-N2ut2lP8M-1ZuJRSQSM:b-896fix) ([raw file](https://github.com/contember/admin/blob/c46033bd1163b7e1ceffc196e6778181efd2c286/packages/binding/src/dao/Environment.ts#L48)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

why not withSubtreeChild? 
</blockquote></details>

Done.
___
*[`packages/binding/src/dao/Environment.ts` line 65 at r4](https://reviewable.io/reviews/contember/admin/321#-N2uaIOO7pfHBACJvIjj:-N2ut33K9vQr5L7dyTyB:b9ufi3o) ([raw file](https://github.com/contember/admin/blob/c46033bd1163b7e1ceffc196e6778181efd2c286/packages/binding/src/dao/Environment.ts#L65)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

given that we store reference to parent environment, why do we need to store the entire path?
</blockquote></details>

we don't, but it is easier to process this.
___
*[`packages/binding/src/dao/Environment.ts` line 232 at r4](https://reviewable.io/reviews/contember/admin/321#-N2uiQgDAr84Le39LYvP:-N2utBf31uApMESxw48u:b-k0t5sc) ([raw file](https://github.com/contember/admin/blob/c46033bd1163b7e1ceffc196e6778181efd2c286/packages/binding/src/dao/Environment.ts#L232)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

would it be possible to get actually more of a tree like structure? i.e sth like

~~~
RootEntity{List?}Node(entitySchema, filter, cardinality)
  ColumnNode(parent, fieldSchema)
  InnerEntityNode(parent, fieldSchema, entitySchema, filter, cardinality)
  InnerEntityListNode(parent, fieldSchema, entitySchema, filter, cardinality)
~~~
</blockquote></details>

overkill imho
___
*[`packages/binding/src/dao/Environment.ts` line 238 at r4](https://reviewable.io/reviews/contember/admin/321#-N2uhflU49qdy0Kvq7OD:-N2usThp-WSGmY5Q-UYI:ba1s0sc) ([raw file](https://github.com/contember/admin/blob/c46033bd1163b7e1ceffc196e6778181efd2c286/packages/binding/src/dao/Environment.ts#L238)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

do we need reference to parent environment, or would reference to parent "tree node" be enough?
</blockquote></details>

we use parent environment in marker factory. rebuilding an environment is more error prone
___
*[`packages/binding/src/dao/Environment.ts` line 242 at r4](https://reviewable.io/reviews/contember/admin/321#-N2udzXb-vtQohUCOIkR:-N2uu2oBDJ6mQJZdfD9y:b-65407b) ([raw file](https://github.com/contember/admin/blob/c46033bd1163b7e1ceffc196e6778181efd2c286/packages/binding/src/dao/Environment.ts#L242)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

is there a reason why do we store entity name instead of reference entity schema object?
</blockquote></details>

no particular reason.
___
*[`packages/binding/src/dao/Environment.ts` line 249 at r4](https://reviewable.io/reviews/contember/admin/321#-N2ueNLL0lnUMk2huiJz:-N2uuBRK4dh5-6lBy4bH:b-65407b) ([raw file](https://github.com/contember/admin/blob/c46033bd1163b7e1ceffc196e6778181efd2c286/packages/binding/src/dao/Environment.ts#L249)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

is there a reason why do we store path as string instead of references to field schema object(s)?
</blockquote></details>

no particular reason.
___
*[`packages/binding/src/dao/TreeNodeEnvironmentFactory.ts` line 53 at r4](https://reviewable.io/reviews/contember/admin/321#-N2uRy2W92UhStbBrKdL:-N2uxfZt4prZwiFSbYhe:b-896fix) ([raw file](https://github.com/contember/admin/blob/c46033bd1163b7e1ceffc196e6778181efd2c286/packages/binding/src/dao/TreeNodeEnvironmentFactory.ts#L53)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

* incosistent naming with `createEnvironmentForEntityListSubtree` (should be just `entity` or `singleEntity`)
* inconsistent line order of declaration & assignments
</blockquote></details>

Done.
___
*[`packages/binding/src/dao/TreeNodeEnvironmentFactory.ts` line 96 at r4](https://reviewable.io/reviews/contember/admin/321#-N2uTAqK2g7qGPTY5x7H:-N2uuKw06XiiuqXmKo2n:b-896fix) ([raw file](https://github.com/contember/admin/blob/c46033bd1163b7e1ceffc196e6778181efd2c286/packages/binding/src/dao/TreeNodeEnvironmentFactory.ts#L96)):*
> ```XML
> 
> 		return this.traverseHasOnePath(
> 			environment,
> ```

Done.
___
*[`packages/binding/src/dao/TreeNodeEnvironmentFactory.ts` line 169 at r4](https://reviewable.io/reviews/contember/admin/321#-N2uTakX9vHEfeDVPHX6:-N2uy6D8024sy3SD4Fs6:b-896fix) ([raw file](https://github.com/contember/admin/blob/c46033bd1163b7e1ceffc196e6778181efd2c286/packages/binding/src/dao/TreeNodeEnvironmentFactory.ts#L169)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

maybe extract "describeField"?
</blockquote></details>

Done.
___
*[`packages/binding/src/dao/TreeNodeEnvironmentHelper.ts` line 38 at r3](https://reviewable.io/reviews/contember/admin/321#-N2qMdkYEowCp2jZ40Fg:-N2utir165yTPEEUgWSQ:b-896fix) ([raw file](https://github.com/contember/admin/blob/695f424b409c584cc4d5adba186cf555dd67561f/packages/binding/src/dao/TreeNodeEnvironmentHelper.ts#L38)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

`zero-to-many` is better than `many` but in `isCreating === true` case it should still be `zero` (to be consistent with isCreating in createEnvironmentForEntitySubtree case)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-25 14:11 UTC, JanTvrdik reviewed
> Reviewed 1 of 3 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/321)* status: all files reviewed, 10 unresolved discussions (waiting on @JanTvrdik and @matej21)



<!-- Sent from Reviewable.io -->

2022-05-25 14:16 UTC, matej21 reviewed
> *[Reviewable](https://reviewable.io/reviews/contember/admin/321)* status: all files reviewed, 9 unresolved discussions (waiting on @JanTvrdik and @matej21)

___
*[`packages/binding/src/dao/Environment.ts` line 65 at r4](https://reviewable.io/reviews/contember/admin/321#-N2uaIOO7pfHBACJvIjj:-N2vZGwAB4iot9qXgCR5:b-896fix) ([raw file](https://github.com/contember/admin/blob/c46033bd1163b7e1ceffc196e6778181efd2c286/packages/binding/src/dao/Environment.ts#L65)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

Why do you think so? Building the path can be done in one for loop that could be put into a method. That does not seem like a good enough reason to duplicate it for each "tree node". You also end-up comparing the path repeatedly in `Environment.merge` (because the recursive merge of parents).
</blockquote></details>

Done.
___
*[`packages/binding/src/dao/Environment.ts` line 232 at r4](https://reviewable.io/reviews/contember/admin/321#-N2uiQgDAr84Le39LYvP:-N2vZHVbDu52lGiawcrv:b-896fix) ([raw file](https://github.com/contember/admin/blob/c46033bd1163b7e1ceffc196e6778181efd2c286/packages/binding/src/dao/Environment.ts#L232)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

why? currently you have tree like data in not tree like structure

basically the problem is that you've added parent reference but the rest of the environment structure was not adjusted

three of the options (subtree, subtreeLocation and parent) are related but this relation is not captured in types resutling in runtime checks

why is it imporant to track rootType (list vs. entity) but not childType (hasOne vs. hasMany vs. column)
</blockquote></details>

Done.
___
*[`packages/binding/src/dao/Environment.ts` line 242 at r4](https://reviewable.io/reviews/contember/admin/321#-N2udzXb-vtQohUCOIkR:-N2vZHyU1ZxH4TYF0jP8:b-896fix) ([raw file](https://github.com/contember/admin/blob/c46033bd1163b7e1ceffc196e6778181efd2c286/packages/binding/src/dao/Environment.ts#L242)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

but wouldn't it make everything easier?

it avoids the validation asymmetry (currently some of validation is in `assert*` methods and some validation is in `get*` methods, because you are both "resolving" the schema & validating instead of just resolving and validation being side-effect of the tree being resolved)

it avoids the repeated field schema resolution done in `withSubtreeChild`

it avoids repeated entity schema resolution in getEntityField call from TreeNodeEnvironmentFactory.assertFieldValid, because at that point it should be already resolved
</blockquote></details>

Done.
___
*[`packages/binding/src/dao/TreeNodeEnvironmentFactory.ts` line 139 at r4](https://reviewable.io/reviews/contember/admin/321#-N2uQ1Rd7IpGMuvs51Tr:-N2vZVe6A26KEh6TVUHL:b-896fix) ([raw file](https://github.com/contember/admin/blob/c46033bd1163b7e1ceffc196e6778181efd2c286/packages/binding/src/dao/TreeNodeEnvironmentFactory.ts#L139)):*
> ```XML
> 		const treeLocation = environment.getSubtreeLocation()
> 		const relation = this.getField(environment, field, field => {
> 			if (field.__typename !== '_Relation') {
> ```

Done.
___
*[`packages/binding/src/dao/TreeNodeEnvironmentFactory.ts` line 147 at r4](https://reviewable.io/reviews/contember/admin/321#-N2uVJXZ1W-sqK5ZycId:-N2vZVohDrEm4iOFmqzb:b-896fix) ([raw file](https://github.com/contember/admin/blob/c46033bd1163b7e1ceffc196e6778181efd2c286/packages/binding/src/dao/TreeNodeEnvironmentFactory.ts#L147)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

column may not by scalar in the future; maybe extract "describeField"?
</blockquote></details>

Done.
___
*[`packages/binding/src/dao/TreeNodeEnvironmentFactory.ts` line 152 at r4](https://reviewable.io/reviews/contember/admin/321#-N2uTN1k2YnMF3pevywF:-N2vZW6X4QyNz_HgOR32:b-896fix) ([raw file](https://github.com/contember/admin/blob/c46033bd1163b7e1ceffc196e6778181efd2c286/packages/binding/src/dao/TreeNodeEnvironmentFactory.ts#L152)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

maybe extract "describeField"?
</blockquote></details>

Done.
___
*[`packages/binding/src/dao/TreeNodeEnvironmentFactory.ts` line 61 at r6](https://reviewable.io/reviews/contember/admin/321#-N2v4QlZ7gydvj0q13jS:-N2vZU_89CkcJzYme7wX:b-896fix) ([raw file](https://github.com/contember/admin/blob/bfe7fbceebb4a0ac789c0ea5b83d1212e14ce3d0/packages/binding/src/dao/TreeNodeEnvironmentFactory.ts#L61)):*
> ```XML
> 			rootWhere = { id: { eq: NIL_UUID } } as const
> 			expectedCardinality = 'zero'
> 			entity = QueryLanguage.desugarUnconstrainedQualifiedSingleEntity(sugaredEntityList, environment)
> ```

Done.
___
*[`packages/binding/src/dao/TreeNodeEnvironmentFactory.ts` line 171 at r6](https://reviewable.io/reviews/contember/admin/321#-N2vIoif1p8w7pYhxVD2:-N2vZWQqBmgcBaNduPbT:b-896fix) ([raw file](https://github.com/contember/admin/blob/bfe7fbceebb4a0ac789c0ea5b83d1212e14ce3d0/packages/binding/src/dao/TreeNodeEnvironmentFactory.ts#L171)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

how is it possible for `treeLocation.entity` do not exist? Should't it always be validated before it's constructed?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-26 07:41 UTC, JanTvrdik requested changes
> *[Reviewable](https://reviewable.io/reviews/contember/admin/321)* status: all files reviewed, 21 unresolved discussions (waiting on @matej21)

___
*[`ee/admin-server/public/_panel/pages/userInvite.tsx` line 8 at r7](https://reviewable.io/reviews/contember/admin/321#-N2zIl8g7LyN-gPKVNDG:-N2zIl8g7LyN-gPKVNDH:undefined) ([raw file](https://github.com/contember/admin/blob/fc1abd31ae539de70d57cf84db738bab39a06a0b/ee/admin-server/public/_panel/pages/userInvite.tsx#L8)):*
> ```XML
> 
> 	const env = useEnvironment()
> 	const inviteMethod = env.getVariable('inviteMethod') as InviteMethod | undefined
> ```





_Suggestion:_
```XML
const inviteMethod = env.getVariable('inviteMethod', undefined) as InviteMethod | undefined
```
___
*[`packages/binding/src/dao/Environment.ts` line 15 at r7](https://reviewable.io/reviews/contember/admin/321#-N2wT9ni0111Rt7y910H:-N2wT9njE9oNzIdDbakz:bmhvcbz) ([raw file](https://github.com/contember/admin/blob/fc1abd31ae539de70d57cf84db738bab39a06a0b/packages/binding/src/dao/Environment.ts#L15)):*
> ```XML
> 	public static create() {
> 		return new Environment({
> 			labelMiddleware: label => label,
> ```

The label middleware feels extremely out-of-scope for `Environment`, as it has nothing to do with data binding. The best possible solution I've come up with is to 

1) allow arbitrary values in variables (functions have to be provided using the long "factory" syntax)
2) (optional) add Symbol support for variable keys and introduce Symbol for `labelMiddleware`
3) put labelMiddleware to variables
4) move `setLabelMiddleware` and `applyLabelMiddleware` from `Environment` to `packages/admin/src/components/bindingFacade/environment/SideDimensions.tsx`
___
*[`packages/binding/src/dao/Environment.ts` line 21 at r7](https://reviewable.io/reviews/contember/admin/321#-N2wb3WO7tD4Oh6cBhbh:-N2wb3WO7tD4Oh6cBhbi:b-bjlac8) ([raw file](https://github.com/contember/admin/blob/dae4276a331eae2118de0a9b00a93e72fc8dc29b/packages/binding/src/dao/Environment.ts#L21)):*
> ```XML
> 	}
> 
> 	public hasName(name: keyof Environment.NameStore): boolean {
> ```

needs to be deprecated before removing

~~~ts
/** @deprecated */
public hasName(key: string): boolean {
    console.warn('Environment.hasName() is deprecated, use Environment.hasVariable() or Environment.hasParameter() instead.')
    return key in this.options.variables || key in this.options.parameters
}
~~~
___
*[`packages/binding/src/dao/Environment.ts` line 39 at r7](https://reviewable.io/reviews/contember/admin/321#-N2wc-gXBwulTjmN-ZiF:-N2wc-gXBwulTjmN-ZiG:b-s5l7qk) ([raw file](https://github.com/contember/admin/blob/dae4276a331eae2118de0a9b00a93e72fc8dc29b/packages/binding/src/dao/Environment.ts#L39)):*
> ```XML
> 	}
> 
> 	public getDimensionOrElse<F>(dimensionName: keyof Environment.SelectedDimensions, fallback: F): string[] | F {
> ```

should remain
___
*[`packages/binding/src/dao/Environment.ts` line 46 at r7](https://reviewable.io/reviews/contember/admin/321#-N2wcOTV0XjLRWuSSEtK:-N2wcOTV0XjLRWuSSEtL:b-ox6041) ([raw file](https://github.com/contember/admin/blob/dae4276a331eae2118de0a9b00a93e72fc8dc29b/packages/binding/src/dao/Environment.ts#L46)):*
> ```XML
> 	}
> 
> 	public getValue<V extends Environment.Value = Environment.Value>(name: keyof Environment.NameStore): V {
> ```

needs to be deprecated before removing
also note that there are projects relying on this to return undefined when value does not exist
___
*[`packages/binding/src/dao/Environment.ts` line 70 at r7](https://reviewable.io/reviews/contember/admin/321#-N2wZUP3-Q4S83zveyJV:-N2wZUP3-Q4S83zveyJW:b-8dpded) ([raw file](https://github.com/contember/admin/blob/fc1abd31ae539de70d57cf84db738bab39a06a0b/packages/binding/src/dao/Environment.ts#L70)):*
> ```XML
> 	public getVariable<F>(key: string, fallback: F): Environment.Value | F
> 	public getVariable(key: string): Environment.Value
> 	public getVariable<F>(key: string, fallback?: F): Environment.Value | F {
> ```

I'm not a big fan of method overloads. Wouldn't it be better to add `getVariable` (throwing exception unlike getValue in current implementation) and `getVariableOrElse` methods?
___
*[`packages/binding/src/dao/Environment.ts` line 80 at r7](https://reviewable.io/reviews/contember/admin/321#-N2wYTCG5vle4Zll0rfY:-N2wYTCG5vle4Zll0rfZ:undefined) ([raw file](https://github.com/contember/admin/blob/fc1abd31ae539de70d57cf84db738bab39a06a0b/packages/binding/src/dao/Environment.ts#L80)):*
> ```XML
> 	}
> 
> 	/** @deprecated use getVariable */
> ```





_Suggestion:_
```XML
/** @deprecated use getVariable or getParameter instead */
```
___
*[`packages/binding/src/dao/Environment.ts` line 81 at r7](https://reviewable.io/reviews/contember/admin/321#-N2wabt09OeTvzbnmhJs:-N2wabt11w7CHW0pzimP:undefined) ([raw file](https://github.com/contember/admin/blob/fc1abd31ae539de70d57cf84db738bab39a06a0b/packages/binding/src/dao/Environment.ts#L81)):*
> ```XML
> 
> 	/** @deprecated use getVariable */
> 	public getValueOrElse<F>(key: string, fallback: F): Environment.Value | F {
> ```





_Suggestion:_
```XML
public getValueOrElse<F, V extends Environment.Value = Environment.Value>(key: string, fallback: F): V | F
```
___
*[`packages/binding/src/dao/Environment.ts` line 82 at r7](https://reviewable.io/reviews/contember/admin/321#-N2wXfIT6JczWa32mvvX:-N2wXfIT6JczWa32mvvY:undefined) ([raw file](https://github.com/contember/admin/blob/fc1abd31ae539de70d57cf84db738bab39a06a0b/packages/binding/src/dao/Environment.ts#L82)):*
> ```XML
> 	/** @deprecated use getVariable */
> 	public getValueOrElse<F>(key: string, fallback: F): Environment.Value | F {
> 		return this.getVariable(key, fallback)
> ```





_Suggestion:_
```XML
console.warn('Environment.getValueOrElse is deprecated, use getVariable or getParameter instead.')
return this.getVariable(key, undefined) ?? this.getParameter(key, fallback)
```
___
*[`packages/binding/src/dao/Environment.ts` line 134 at r7](https://reviewable.io/reviews/contember/admin/321#-N2wdOFx0946ve3rLbHa:-N2wdOFx0946ve3rLbHb:b-727kxo) ([raw file](https://github.com/contember/admin/blob/dae4276a331eae2118de0a9b00a93e72fc8dc29b/packages/binding/src/dao/Environment.ts#L134)):*
> ```XML
> 	}
> 
> 	public applySystemMiddleware<
> ```

needs to be deprecated before removing (because it is used by end users)
___
*[`packages/binding/src/queryLanguage/Parser.ts` line 731 at r7](https://reviewable.io/reviews/contember/admin/321#-N2zHwNOB2JYAreZKI_F:-N2zHwNOB2JYAreZKI_G:bbemd3o) ([raw file](https://github.com/contember/admin/blob/fc1abd31ae539de70d57cf84db738bab39a06a0b/packages/binding/src/queryLanguage/Parser.ts#L731)):*
> ```XML
> 
> 		return this.ACTION(() => {
> 			if (import.meta.env.DEV && variableName === 'rootWhereAsFilter') {
> ```

can we deprecate both of them? what is `rootFilter` needed for?
___
*[`packages/binding/src/queryLanguage/Parser.ts` line 749 at r7](https://reviewable.io/reviews/contember/admin/321#-N2zHSNBB5u6dMx0ksvP:-N2zHSNBB5u6dMx0ksvQ:b-mgerb3) ([raw file](https://github.com/contember/admin/blob/fc1abd31ae539de70d57cf84db738bab39a06a0b/packages/binding/src/queryLanguage/Parser.ts#L749)):*
> ```XML
> 				const dimensionValue = Parser.environment.getDimension(variableName)
> 				if (dimensionValue.length > 1) {
> 					throw new BindingError(`The variable \$${variableName} resolved to a dimension which exists but contains ${dimensionValue.length} values. It has to contain exactly one. ` +
> ```

the previous formatting was better.



_Suggestion:_
```XML
				if (dimensionValue.length > 1) {
					throw new BindingError(
						`The variable \$${variableName} resolved to a dimension which exists but contains ${dimensionValue.length} values. It has to contain exactly one. ` +
						`Perhaps you forgot to set the 'maxItems' prop of your DimensionsSwitcher?`,
					)
				}
```
___
*[`packages/binding/src/dao/TreeNodeEnvironmentFactory.ts` line 81 at r7](https://reviewable.io/reviews/contember/admin/321#-N2wg5PkAzSIKgc5TzsN:-N2wg5PkAzSIKgc5TzsO:bzbbzn9) ([raw fil [...]

2022-05-26 09:21 UTC, matej21 reviewed
> *[Reviewable](https://reviewable.io/reviews/contember/admin/321)* status: 43 of 49 files reviewed, 22 unresolved discussions (waiting on @deprecated and @JanTvrdik)

___
*[`ee/admin-server/public/_panel/pages/userInvite.tsx` line 8 at r7](https://reviewable.io/reviews/contember/admin/321#-N2zIl8g7LyN-gPKVNDG:-N2zareADKx23T7ZC_Mn:b-896fix) ([raw file](https://github.com/contember/admin/blob/fc1abd31ae539de70d57cf84db738bab39a06a0b/ee/admin-server/public/_panel/pages/userInvite.tsx#L8)):*
> ```XML
> 
> 	const env = useEnvironment()
> 	const inviteMethod = env.getVariable('inviteMethod') as InviteMethod | undefined
> ```

Done.
___
*[`packages/binding/src/dao/Environment.ts` line 15 at r7](https://reviewable.io/reviews/contember/admin/321#-N2wT9ni0111Rt7y910H:-N2zdxTr0CbKWmrNTtWF:b-6d0y78) ([raw file](https://github.com/contember/admin/blob/fc1abd31ae539de70d57cf84db738bab39a06a0b/packages/binding/src/dao/Environment.ts#L15)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

The label middleware feels extremely out-of-scope for `Environment`, as it has nothing to do with data binding. The best possible solution I've come up with is to 

1) allow arbitrary values in variables (functions have to be provided using the long "factory" syntax)
2) (optional) add Symbol support for variable keys and introduce Symbol for `labelMiddleware`
3) put labelMiddleware to variables
4) move `setLabelMiddleware` and `applyLabelMiddleware` from `Environment` to `packages/admin/src/components/bindingFacade/environment/SideDimensions.tsx`
</blockquote></details>

Don't like your solution.
___
*[`packages/binding/src/dao/Environment.ts` line 21 at r7](https://reviewable.io/reviews/contember/admin/321#-N2wb3WO7tD4Oh6cBhbh:-N2zbvE35OwqKtYOpBLb:b-896fix) ([raw file](https://github.com/contember/admin/blob/dae4276a331eae2118de0a9b00a93e72fc8dc29b/packages/binding/src/dao/Environment.ts#L21)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

needs to be deprecated before removing

~~~ts
/** @deprecated */
public hasName(key: string): boolean {
    console.warn('Environment.hasName() is deprecated, use Environment.hasVariable() or Environment.hasParameter() instead.')
    return key in this.options.variables || key in this.options.parameters
}
~~~
</blockquote></details>

Done.
___
*[`packages/binding/src/dao/Environment.ts` line 22 at r7](https://reviewable.io/reviews/contember/admin/321#-N2zKrp43_eurIkROWmL:-N2zc-44-gti2htVj5Fh:b-896fix) ([raw file](https://github.com/contember/admin/blob/fc1abd31ae539de70d57cf84db738bab39a06a0b/packages/binding/src/dao/Environment.ts#L22)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

admin currently uses `SubTree` (with uppercase T) everywhere, so so this should be consistent
</blockquote></details>

Done.
___
*[`packages/binding/src/dao/Environment.ts` line 27 at r7](https://reviewable.io/reviews/contember/admin/321#-N2w1DG38aOe-3zr5_PP:-N2zclmX1sC_uyDSjiXz:b-896fix) ([raw file](https://github.com/contember/admin/blob/fc1abd31ae539de70d57cf84db738bab39a06a0b/packages/binding/src/dao/Environment.ts#L27)):*
> ```XML
> 			if (!node) {
> 				throw new BindingError('Not in a subtree')
> 			}
> ```

Done.
___
*[`packages/binding/src/dao/Environment.ts` line 34 at r7](https://reviewable.io/reviews/contember/admin/321#-N2w21oV8M6TMXdrsvze:-N2zcnSG4i1npxIhBqE5:b-896fix) ([raw file](https://github.com/contember/admin/blob/fc1abd31ae539de70d57cf84db738bab39a06a0b/packages/binding/src/dao/Environment.ts#L34)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

the naming is a bit scuffed, this needs to be `getSubtreeNode()` or maybe just `getNode()`
</blockquote></details>

Done.
___
*[`packages/binding/src/dao/Environment.ts` line 39 at r7](https://reviewable.io/reviews/contember/admin/321#-N2wc-gXBwulTjmN-ZiF:-N2zcnjXBLpCem7I90A4:b3kre) ([raw file](https://github.com/contember/admin/blob/dae4276a331eae2118de0a9b00a93e72fc8dc29b/packages/binding/src/dao/Environment.ts#L39)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

should remain
</blockquote></details>

?
___
*[`packages/binding/src/dao/Environment.ts` line 41 at r7](https://reviewable.io/reviews/contember/admin/321#-N2vo7zg0CvZ5NXjoHTV:-N2zctrsAxu2h2TTBeO_:bekolt5) ([raw file](https://github.com/contember/admin/blob/fc1abd31ae539de70d57cf84db738bab39a06a0b/packages/binding/src/dao/Environment.ts#L41)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

maybe `withSubtreeRoot`?
</blockquote></details>

subtree implies root, "subtree root" is never used
___
*[`packages/binding/src/dao/Environment.ts` line 46 at r7](https://reviewable.io/reviews/contember/admin/321#-N2wcOTV0XjLRWuSSEtK:-N2zcz-cBnY5rgnvbBcK:b3kre) ([raw file](https://github.com/contember/admin/blob/dae4276a331eae2118de0a9b00a93e72fc8dc29b/packages/binding/src/dao/Environment.ts#L46)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

needs to be deprecated before removing
also note that there are projects relying on this to return undefined when value does not exist
</blockquote></details>

?
___
*[`packages/binding/src/dao/Environment.ts` line 70 at r7](https://reviewable.io/reviews/contember/admin/321#-N2wZUP3-Q4S83zveyJV:-N2ze0AA15KOl_aKHbIz:b-wxax55) ([raw file](https://github.com/contember/admin/blob/fc1abd31ae539de70d57cf84db738bab39a06a0b/packages/binding/src/dao/Environment.ts#L70)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

I'm not a big fan of method overloads. Wouldn't it be better to add `getVariable` (throwing exception unlike getValue in current implementation) and `getVariableOrElse` methods?
</blockquote></details>

I like this pattern (when used with a caution)
___
*[`packages/binding/src/dao/Environment.ts` line 80 at r7](https://reviewable.io/reviews/contember/admin/321#-N2wYTCG5vle4Zll0rfY:-N2zdTyz-emHub61qT91:b-896fix) ([raw file](https://github.com/contember/admin/blob/fc1abd31ae539de70d57cf84db738bab39a06a0b/packages/binding/src/dao/Environment.ts#L80)):*
> ```XML
> 	}
> 
> 	/** @deprecated use getVariable */
> ```

Done.
___
*[`packages/binding/src/dao/Environment.ts` line 81 at r7](https://reviewable.io/reviews/contember/admin/321#-N2wabt09OeTvzbnmhJs:-N2zdUI9DxEcCqElhSpf:b-896fix) ([raw file](https://github.com/contember/admin/blob/fc1abd31ae539de70d57cf84db738bab39a06a0b/packages/binding/src/dao/Environment.ts#L81)):*
> ```XML
> 
> 	/** @deprecated use getVariable */
> 	public getValueOrElse<F>(key: string, fallback: F): Environment.Value | F {
> ```

Done.
___
*[`packages/binding/src/dao/Environment.ts` line 82 at r7](https://reviewable.io/reviews/contember/admin/321#-N2wXfIT6JczWa32mvvX:-N2zdb_W1v2pOUCQKsOb:b-896fix) ([raw file](https://github.com/contember/admin/blob/fc1abd31ae539de70d57cf84db738bab39a06a0b/packages/binding/src/dao/Environment.ts#L82)):*
> ```XML
> 	/** @deprecated use getVariable */
> 	public getValueOrElse<F>(key: string, fallback: F): Environment.Value | F {
> 		return this.getVariable(key, fallback)
> ```

Done.
___
*[`packages/binding/src/dao/Environment.ts` line 134 at r7](https://reviewable.io/reviews/contember/admin/321#-N2wdOFx0946ve3rLbHa:-N2zdayaBP4rS-oLppEe:b3kre) ([raw file](https://github.com/contember/admin/blob/dae4276a331eae2118de0a9b00a93e72fc8dc29b/packages/binding/src/dao/Environment.ts#L134)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

needs to be deprecated before removing (because it is used by end users)
</blockquote></details>

?
___
*[`packages/binding/src/dao/Environment.ts` line 232 at r7](https://reviewable.io/reviews/contember/admin/321#-N2w3EUb7Kx9NLRhM8sa:-N2zddPh9rewzKhtQfLa:bauz6oh) ([raw file](https://github.com/contember/admin/blob/fc1abd31ae539de70d57cf84db738bab3 [...]

2022-05-26 11:57 UTC, JanTvrdik requested changes
> Reviewed 5 of 6 files at r8, 8 of 8 files at r9, 1 of 2 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/321)* status: all files reviewed, 2 unresolved discussions (waiting on @matej21)

___
*[`packages/binding/src/dao/Environment.ts` line 70 at r7](https://reviewable.io/reviews/contember/admin/321#-N2wZUP3-Q4S83zveyJV:-N3-Daa_5SF0hg5p9AsB:bgfmdfh) ([raw file](https://github.com/contember/admin/blob/fc1abd31ae539de70d57cf84db738bab39a06a0b/packages/binding/src/dao/Environment.ts#L70)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

I like this pattern (when used with a caution)
</blockquote></details>

please reconsider
___
*[`packages/binding/src/dao/Environment.ts` line 78 at r11](https://reviewable.io/reviews/contember/admin/321#-N3-CjvXECRiZ1dNLYV3:-N3-CjvXECRiZ1dNLYV4:b5oxwd4) ([raw file](https://github.com/contember/admin/blob/03f636f5aea35d456aae739a3f508d2a41f8eb24/packages/binding/src/dao/Environment.ts#L78)):*
> ```XML
> 
> 	/** @deprecated use getVariable or getParameter */
> 	public getValueOrElse<F, V extends Environment.Value = Environment.Value>(key: string, fallback: F): V | F {
> ```

MISSING deprecation for getValue() and getDimensionOrElse()
note that getValue must return undefined when value is not defined, instead of throwing exception


<!-- Sent from Reviewable.io -->

2022-05-26 12:20 UTC, JanTvrdik approved these changes
> Reviewed 5 of 5 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/admin/321)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matej21)



<!-- Sent from Reviewable.io -->

2022-05-26 13:23 UTC, merged