Use transparent background for most cases
contember/admin pull request #410
Opened 2022-08-17 11:36 UTC by attitude

- Slow queries will transition to dimmed background to further amplify the UI is not ready to be used while spinner is active

Closes: https://github.com/contember/private-issues/issues/129

2022-08-18 07:44 UTC, JanTvrdik commented on packages/ui/src/components/ContainerSpinner.tsx
> +	}, [])
is it possible to do this in CSS?

2022-08-18 07:45 UTC, JanTvrdik requested changes
> *[Reviewable](https://reviewable.io/reviews/contember/admin/410)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @attitude and @matej21)

___
*[`packages/ui/src/components/ContainerSpinner.tsx` line 28 at r1](https://reviewable.io/reviews/contember/admin/410#-N9juNGa-_l8IWXhg-D8:-N9juNGa-_l8IWXhg-D9:bs1xngw) ([raw file](https://github.com/contember/admin/blob/3da0bb9f2d94bdacfe043da9c851ffa3834f57bf/packages/ui/src/components/ContainerSpinner.tsx#L28)):*
> ```XML
> 			useComponentClassName('containerSpinner'),
> 			toEnumViewClass(size),
> 			isSlow ? 'is-dimmed' : undefined,
> ```

is it possible to do this in CSS?


<!-- Sent from Reviewable.io -->

2022-08-18 14:43 UTC, attitude reviewed
> *[Reviewable](https://reviewable.io/reviews/contember/admin/410)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @JanTvrdik and @matej21)

___
*[`packages/ui/src/components/ContainerSpinner.tsx` line 28 at r1](https://reviewable.io/reviews/contember/admin/410#-N9juNGa-_l8IWXhg-D8:-N9lOthk0ou0xw24DmLL:baz2672) ([raw file](https://github.com/contember/admin/blob/3da0bb9f2d94bdacfe043da9c851ffa3834f57bf/packages/ui/src/components/ContainerSpinner.tsx#L28)):*
<details><summary><i>Previously, JanTvrdik (Jan Tvrdík) wrote…</i></summary><blockquote>

is it possible to do this in CSS?
</blockquote></details>

It is possible with CSS animation with some delay and forward fill-mode.


<!-- Sent from Reviewable.io -->

2022-08-30 11:04 UTC, JanTvrdik approved these changes
> *[Reviewable](https://reviewable.io/reviews/contember/admin/410)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matej21)



<!-- Sent from Reviewable.io -->

2022-08-30 11:15 UTC, merged