[WIP] Routing parameters substitution
contember/admin pull request #53
Opened 2021-09-15 15:35 UTC by matej21

Closes #

### Checks
- [ ] The changes and implementation strategy have been consulted with the maintainers.
- [ ] The code passes all the checks (Run `pnpm run check`).

2021-09-17 16:23 UTC, VojtaStanek requested changes

2021-09-17 16:23 UTC, VojtaStanek commented on packages/admin/src/routing/useRoutingLink.ts
> +const completeRequest = (request: IncompleteRequestState, currentRequest: RequestState, resolveParameter: RoutingParameterResolver): RequestState => {
I would inline this function

2021-09-17 16:23 UTC, VojtaStanek commented on packages/admin/src/routing/types.ts
> +export type IncompleteRequestState = Partial<RequestState<DynamicRequestParameters>> & { pageName: string } | null
Why union with null?

2021-09-17 16:23 UTC, VojtaStanek commented on packages/admin/src/routing/types.ts
> +export type RequestParameterValue<Extra extends RoutingParameter = never> = string | undefined | Extra;
Why is it generic? Wouldn't it be better (more readable) to have the extra union on "use-side"?

2021-09-17 16:23 UTC, VojtaStanek commented on packages/admin/src/routing/useRoutingLink.ts
> +			return [name, resolveParameters(value, resolveParameter)]
Why this recursive call?

2021-09-20 11:11 UTC, JanTvrdik commented on packages/binding/src/queryLanguage/Parser.ts
> +		functionCall: ParsedFunctionCall
e.g.

2021-12-16 09:57 UTC, merged